#orbs:
#  heroku: circleci/heroku@1.0.0
#
#workflows:
#  build-deploy:
#    jobs:
#      - build
#  heroku_deploy:
#  - deploy:
#    requires:
#      - build
#    filters:
#      branches:
#        only: master
#
#jobs:
#  build:
#    steps:
#      - run: npm install
#      - save-cache:
#        paths:
#        - node_modules
#        key: v1-dependencies-{{ checksum "package.json" }}
#      - run: npm run build
#
#  deploy:
#    executor: heroku/default
#    steps:
#      - checkout
#      - heroku/install
#      - run:
#          name: Deploy Master to Heroku
#          command: |
#            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
#          only-branch: master

version: 2
  jobs:
    build:
      docker:
        - image: circleci/node:8
      steps:
        - checkout
        - restore_cache: # special step to restore the dependency cache
      key: dependency-cache-{{ checksum "package.json" }}
        - run:
            name: Setup Dependencies
            command: npm install
        - run:
            name: Setup Code Climate test-reporter
            command: |
              curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter            chmod +x ./cc-test-reporter
        - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
