version: 2
orbs:
  heroku: circleci/heroku@1.0.0

jobs:
  build:
    steps:
      - run: npm install
      - save-cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run build

  deploy:
    docker: # run the steps with Docker
      executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
          only-branch: master

workflows:
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master